"""Add TourImage model

Revision ID: 618b21a2ed34
Revises: ba6f6db5b18d
Create Date: 2024-10-20 23:24:30.543152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618b21a2ed34'
down_revision = 'ba6f6db5b18d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=100), nullable=True))

    op.drop_table('tour_image')
    # ### end Alembic commands ###
