"""Add original_price and discount_percentage to Tour

Revision ID: c0b34b3adbfb
Revises: b5f133aa16ee
Create Date: 2024-10-19 22:35:15.044523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b34b3adbfb'
down_revision = 'b5f133aa16ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount_percentage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('original_price')

    # ### end Alembic commands ###
